using FlowWire.Core;

namespace FlowWire.Engine.Internals;

/// <summary>
/// Represents a decision/command generated by the workflow logic to be executed by the engine.
/// Is a lightweight struct pointing to payload data in the Arena.
/// </summary>
public readonly struct Command(EventType type, int offset, int length)
{
    public EventType Type { get; } = type;
    public int PayloadOffset { get; } = offset;
    public int PayloadLength { get; } = length;
}
